source("MainData.R")
png("plot3.png",width = 480,height = 480)
par(mfrow = c(1,1))
plot(data$Time,data$Sub_metering_1,ylab = "Energy Sub metering",col = "black",type = "l",xlab = "")
lines(data$Time,data$Sub_metering_2,col = "red")
lines(data$Time,data$Sub_metering_3,col = "blue")
legend("topright", lty = 1, col = c("black","red","blue"),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()